---  # testing.yml

- hosts: localhost

  # Variables in order of appearance

  vars:
    ansible_python_interpreter: /usr/bin/python3
    firstuser_login: microlinux
    firstuser_name: Microlinux
    hostname: squidbox
    domain_lan: sandbox.lan
    interface_wan: enp1s0
    address_wan: "{{ansible_default_ipv4.address}}"
    prefix_wan: "{{ansible_default_ipv4.prefix}}"
    gateway_wan: "{{ansible_default_ipv4.gateway}}"
    interface_lan: enp2s0
    network_lan: 192.168.3.0/24
    address_lan: 192.168.3.1
    prefix_lan: 24
    dns1: 1.1.1.1
    dns2: 1.0.0.1
    cache_mem: 256 MB

  tasks:

    - name: Open port 3128 for Squid
      ansible.posix.firewalld:
        zone: internal
        service: squid
        state: enabled
        permanent: true
        immediate: true

    - name: Open port 3129 for Squid
      ansible.posix.firewalld:
        zone: internal
        port: 3129/tcp
        state: enabled
        permanent: true
        immediate: true

    - name: Forward port 80 to 3128
      ansible.posix.firewalld:
        zone: internal
        port_forward:
          - port: 80
            proto: tcp
            toport: 3128
            toaddr: "{{address_lan}}"
        state: enabled
        permanent: true
        immediate: true

    - name: Forward port 443 to 3129
      ansible.posix.firewalld:
        zone: internal
        port_forward:
          - port: 443
            proto: tcp
            toport: 3129
            toaddr: "{{address_lan}}"
        state: enabled
        permanent: true
        immediate: true

    - name: Install Squid
      ansible.builtin.dnf:
        name: squid
        state: present

    - name: Make sure Squid is enabled and started
      ansible.builtin.service:
        name: squid
        enabled: true
        state: started

    - name: Configure Squid
      ansible.builtin.template:
        src: squid.conf.j2
        dest: /etc/squid/squid.conf
        owner: root
        group: squid
        mode: 0640
      notify: Restart Squid

    - name: Create certificate directory
      ansible.builtin.file:
        path: /etc/squid/ssl_cert
        state: directory
        owner: squid
        group: squid
        mode: 0755

    - name: Create self-signed certificate
      ansible.builtin.command:
        cmd: "openssl req -new -newkey rsa:4096 \
              -sha256 -days 3650 -nodes \
              -x509 -extensions v3_ca \
              -keyout /etc/squid/ssl_cert/certificat.pem \
              -out /etc/squid/ssl_cert/certificat.pem \
              -subj '/C=FR/ST=Gard/L=Montpezat/\
              O=Microlinux/OU=IT/CN={{hostname}}.{{domain_lan}}'"
        creates: /etc/squid/ssl_cert/certificat.pem

  handlers:

    - name: Restart Squid
      ansible.builtin.service:
        name: squid
        state: restarted

...
