---  # testing.yml

- hosts: localhost

  # Variables in order of appearance

  vars:
    ansible_python_interpreter: /usr/bin/python3
    firstuser_login: microlinux
    firstuser_name: Microlinux
    hostname: squidbox
    domain_lan: sandbox.lan
    interface_wan: enp1s0
    address_wan: "{{ansible_default_ipv4.address}}"
    prefix_wan: "{{ansible_default_ipv4.prefix}}"
    gateway_wan: "{{ansible_default_ipv4.gateway}}"
    interface_lan: enp2s0
    address_lan: 192.168.3.1
    prefix_lan: 24
    dns1: 1.1.1.1
    dns2: 1.0.0.1

  tasks:

    - name: Make sure FirewallD is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Make sure FirewallD is enabled and started
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Associate external zone to WAN network interface
      ansible.posix.firewalld:
        zone: external
        interface: "{{interface_wan}}"
        state: enabled
        permanent: true
        immediate: true

...
