---  # testing.yml

- hosts: localhost

  # Variables in order of appearance

  vars:
    ansible_python_interpreter: /usr/bin/python3
    firstuser_login: microlinux
    firstuser_name: Microlinux
    hostname: squidbox
    domain_lan: sandbox.lan
    interface_wan: enp1s0
    address_wan: "{{ansible_default_ipv4.address}}"
    prefix_wan: "{{ansible_default_ipv4.prefix}}"
    gateway_wan: "{{ansible_default_ipv4.gateway}}"
    interface_lan: enp2s0
    network_lan: 192.168.3.0/24
    address_lan: 192.168.3.1
    prefix_lan: 24
    dns1: 1.1.1.1
    dns2: 1.0.0.1

  tasks:

    # Passwords and other sensitive data

    - name: Include encrypted variables
      ansible.builtin.include_vars:
        file: vars/secret.yml

    - name: Make sure Postfix and related tools are installed
      ansible.builtin.dnf:
        name: "{{item}} "
        state: present
      loop:
        - cyrus-sasl-plain
        - cyrus-sasl-gssapi
        - cyrus-sasl-lib
        - postfix
        - mailx

    - name: Configure mail relay user
      ansible.builtin.template:
        src: sasl_passwd.j2
        dest: /etc/postfix/sasl_passwd
        owner: root
        group: root
        mode: 0400
      notify: Create hash database for sasl_passwd file

  handlers:
    
    # Postfix

    - name: Create hash database for sasl_passwd file
      ansible.builtin.command:
        cmd: postmap /etc/postfix/sasl_passwd

...
