---  # testing.yml

- hosts: localhost

  # Variables in order of appearance

  vars:
    ansible_python_interpreter: /usr/bin/python3
    firstuser_login: microlinux
    firstuser_name: Microlinux
    hostname: squidbox
    domain_lan: sandbox.lan
    interface_wan: enp1s0
    address_wan: "{{ansible_default_ipv4.address}}"
    prefix_wan: "{{ansible_default_ipv4.prefix}}"
    gateway_wan: "{{ansible_default_ipv4.gateway}}"
    interface_lan: enp2s0
    network_lan: 192.168.3.0/24
    address_lan: 192.168.3.1
    prefix_lan: 24
    dns1: 1.1.1.1
    dns2: 1.0.0.1
    cache_mem: 256 MB

  tasks:

    - name: Open port 3128 for Squid
      ansible.posix.firewalld:
        zone: internal
        service: squid
        state: enabled
        permanent: true
        immediate: true

    - name: Install Squid
      ansible.builtin.dnf:
        name: squid
        state: present

    - name: Configure Squid
      ansible.builtin.template:
        src: squid.conf.j2
        dest: /etc/squid/squid.conf

...
