---  # testing.yml

- hosts: localhost

  # Variables in order of appearance

  vars:
    ansible_python_interpreter: /usr/bin/python3
    firstuser_login: microlinux
    firstuser_name: Microlinux
    hostname: squidbox
    domain_lan: sandbox.lan
    interface_wan: enp1s0
    address_wan: "{{ansible_default_ipv4.address}}"
    prefix_wan: "{{ansible_default_ipv4.prefix}}"
    gateway_wan: "{{ansible_default_ipv4.gateway}}"
    interface_lan: enp2s0
    network_lan: 192.168.3.0/24
    address_lan: 192.168.3.1
    prefix_lan: 24
    dns1: 1.1.1.1
    dns2: 1.0.0.1

  tasks:

    - name: Include encrypted variables
      ansible.builtin.include_vars:
        file: vars/secret.yml

    - name: Install DNF Automatic
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present

    - name: Configure DNF Automatic
      ansible.builtin.template:
        src: automatic.conf.j2
        dest: /etc/dnf/automatic.conf
        owner: root
        group: root
        mode: 0644
      notify: Setup systemd timer for DNF Automatic

    - name: "Reboot every Monday at 03:30"
      ansible.builtin.cron:
        name: "Reboot every Monday at 03:30"
        weekday: "01"
        minute: "30"
        hour: "03"
        user: root
        job: "/usr/bin/systemctl reboot"

  handlers:

    - name: Setup systemd timer for DNF Automatic
      ansible.builtin.systemd_service:
        name: dnf-automatic.timer
        state: started
        enabled: true

...
